# Config file for Air

[build]
  # Command to build the app
  cmd = "go build -o ./bin/api ./cmd/main.go"

  # Binary to watch
  bin = "bin/api"

  # Working directory
  dir = "."

[run]
  cmd = "/app"            

  watch_dir = ["./"]                

  extensions = ["go"]   

[log]
  level = "debug"           

