version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    image: api
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - restaurant
    env_file:
      - .env
  
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - restaurant
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_NAME"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    volumes:
      - ./cmd/migrate/migrations:/migrations
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    networks:
      - restaurant
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["migrate", "-path=/migrations", "-database=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}?sslmode=disable"]

    # command pozostaje pusty, aby umożliwić dynamiczne uruchamianie migracji up/down

volumes:
  db_data:

networks:
  restaurant:
    driver: bridge

