version: "3"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    image: api
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - restaurant
    env_file:
      - .env
  
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    ports:
      - 5432:5432
    # environment:
    #   - POSTGRES_USER=${DB_USER}
    #   - POSTGRES_PASSWORD=${DB_PASSWORD}
    #   - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - restaurant
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_NAME"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  restaurant:
    driver: bridge

